# Generated by Django 5.2.8 on 2025-11-13 10:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='loja_catego_name_629d40_idx'), models.Index(fields=['is_active'], name='loja_catego_is_acti_9d028f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(help_text='Código único fornecido ao cliente', max_length=20, unique=True, verbose_name='Código do Pedido')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAYMENT_UPLOADED', 'Comprovante Enviado'), ('CONFIRMED', 'Confirmado'), ('PROCESSING', 'Em Processamento'), ('READY', 'Pronto para Retirada'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(choices=[('CASH', 'Dinheiro'), ('DEBIT', 'Mpesa'), ('CREDIT', 'M-kesh'), ('PIX', 'E-mola'), ('TRANSFER', 'Banco')], max_length=20, verbose_name='Método de Pagamento')),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='payment_proofs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Comprovante de Pagamento')),
                ('payment_proof_uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Comprovante Enviado em')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Total')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='loja.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único do produto (SKU)', max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Preço por unidade de medida', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Unitário')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço de Custo')),
                ('stock_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Quantidade em Estoque')),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, help_text='Alerta quando o estoque estiver abaixo deste valor', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Estoque Mínimo')),
                ('stock_status', models.CharField(choices=[('IN_STOCK', 'Em Estoque'), ('LOW_STOCK', 'Estoque Baixo'), ('OUT_OF_STOCK', 'Sem Estoque')], default='IN_STOCK', max_length=20, verbose_name='Status do Estoque')),
                ('allows_bulk_sale', models.BooleanField(default=True, help_text='Se verdadeiro, permite vender quantidades fracionadas', verbose_name='Permite Venda Avulsa')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código de Barras')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/', verbose_name='Imagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='loja.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Unitário')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Total')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='loja.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='loja.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(max_length=20, unique=True, verbose_name='Número da Venda')),
                ('status', models.CharField(choices=[('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado')], default='COMPLETED', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(choices=[('CASH', 'Dinheiro'), ('DEBIT', 'Débito'), ('CREDIT', 'Crédito'), ('PIX', 'PIX'), ('TRANSFER', 'Transferência')], max_length=20, verbose_name='Método de Pagamento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Total')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Pago')),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Troco')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='loja.customer', verbose_name='Cliente')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Unitário')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Total')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='loja.product', verbose_name='Produto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='loja.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Item da Venda',
                'verbose_name_plural': 'Itens da Venda',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('abbreviation', models.CharField(max_length=10, unique=True, verbose_name='Abreviação')),
                ('unit_type', models.CharField(choices=[('WEIGHT', 'Peso'), ('VOLUME', 'Pacote'), ('UNIT', 'Unidade'), ('PACKAGE', 'Embalagem')], max_length=20, verbose_name='Tipo de Unidade')),
                ('base_unit_conversion', models.DecimalField(decimal_places=4, default=1.0, help_text='Ex: 1 kg = 1000g (base_unit_conversion = 1000)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Conversão para Unidade Base')),
                ('allows_fraction', models.BooleanField(default=False, help_text='Se verdadeiro, permite vender quantidades fracionadas (ex: 0.5 kg)', verbose_name='Permite Fração')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['abbreviation'], name='loja_unitof_abbrevi_5616ad_idx'), models.Index(fields=['unit_type'], name='loja_unitof_unit_ty_bb5067_idx')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='loja.unitofmeasure', verbose_name='Unidade de Medida'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('MANAGER', 'Gerente'), ('SELLER', 'Vendedor'), ('CUSTOMER', 'Cliente')], default='CUSTOMER', max_length=20, verbose_name='Função')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Avatar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuário',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='WeeklySalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('week_number', models.IntegerField(help_text='Número da semana no ano (1-53)', verbose_name='Número da Semana')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Término')),
                ('total_sales', models.IntegerField(default=0, verbose_name='Total de Vendas')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Receita Total')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Custo Total')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Lucro Total')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Total de Pedidos')),
                ('is_finalized', models.BooleanField(default=False, help_text='Relatório foi processado e finalizado', verbose_name='Finalizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Relatório Semanal de Vendas',
                'verbose_name_plural': 'Relatórios Semanais de Vendas',
                'ordering': ['-year', '-week_number'],
                'indexes': [models.Index(fields=['year', 'week_number'], name='loja_weekly_year_e6feb4_idx'), models.Index(fields=['start_date', 'end_date'], name='loja_weekly_start_d_5e83fa_idx'), models.Index(fields=['is_finalized'], name='loja_weekly_is_fina_df6b34_idx')],
                'unique_together': {('year', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='SellerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.IntegerField(default=0, verbose_name='Total de Vendas')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Receita Total')),
                ('total_items_sold', models.IntegerField(default=0, verbose_name='Total de Itens Vendidos')),
                ('average_sale_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Médio de Venda')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performances', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
                ('weekly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_performances', to='loja.weeklysalesreport', verbose_name='Relatório Semanal')),
            ],
            options={
                'verbose_name': 'Desempenho do Vendedor',
                'verbose_name_plural': 'Desempenhos dos Vendedores',
                'ordering': ['-total_revenue'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PAYMENT_CONFIRM', 'Confirmação de Pagamento'), ('SALE_COMPLETE', 'Venda Concluída'), ('SALE_CANCEL', 'Venda Cancelada'), ('ORDER_CREATE', 'Pedido Criado'), ('ORDER_CONFIRM', 'Pedido Confirmado'), ('STOCK_UPDATE', 'Atualização de Estoque')], max_length=20, verbose_name='Ação')),
                ('model_name', models.CharField(help_text='Nome do modelo afetado', max_length=100, verbose_name='Modelo')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='ID do Objeto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('changes', models.JSONField(blank=True, help_text='JSON com as alterações realizadas', null=True, verbose_name='Alterações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='loja_auditl_user_id_984077_idx'), models.Index(fields=['action', '-created_at'], name='loja_auditl_action_559153_idx'), models.Index(fields=['model_name', 'object_id'], name='loja_auditl_model_n_c91282_idx'), models.Index(fields=['-created_at'], name='loja_auditl_created_7b5fcd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['full_name'], name='loja_custom_full_na_29eb7f_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='loja_custom_phone_086424_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['cpf'], name='loja_custom_cpf_be1e55_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active'], name='loja_custom_is_acti_5ecb81_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['-created_at'], name='loja_custom_created_3ddd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_code'], name='loja_order_order_c_14cb3a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='loja_order_custome_73e35b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='loja_order_status_50b7c1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='loja_order_created_5f6519_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='loja_orderi_order_i_8f40fc_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_number'], name='loja_sale_sale_nu_0b64fb_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['seller', '-created_at'], name='loja_sale_seller__951a89_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', '-created_at'], name='loja_sale_status_e11172_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['-created_at'], name='loja_sale_created_86ec92_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer', '-created_at'], name='loja_sale_custome_d4ab7f_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'product'], name='loja_saleit_sale_id_e2cebd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='loja_produc_code_8f11f2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='loja_produc_name_066cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='loja_produc_categor_50a952_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_status'], name='loja_produc_stock_s_7f0afd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='loja_produc_barcode_394da0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='loja_produc_created_41820c_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='loja_userpr_role_46697c_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['cpf'], name='loja_userpr_cpf_e20835_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_active'], name='loja_userpr_is_acti_3c5db1_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerperformance',
            index=models.Index(fields=['weekly_report', 'seller'], name='loja_seller_weekly__443af6_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerperformance',
            index=models.Index(fields=['seller', '-total_revenue'], name='loja_seller_seller__f47b52_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sellerperformance',
            unique_together={('weekly_report', 'seller')},
        ),
    ]
