# Generated by Django 5.2.8 on 2025-11-13 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SALE_MILESTONE', 'Marco de Vendas'), ('PRODUCT_ADDED', 'Produto Adicionado'), ('LOW_STOCK', 'Estoque Baixo'), ('OUT_OF_STOCK', 'Sem Estoque'), ('ORDER_RECEIVED', 'Pedido Recebido'), ('ORDER_CONFIRMED', 'Pedido Confirmado'), ('PAYMENT_UPLOADED', 'Comprovante Enviado'), ('STOCK_UPDATED', 'Estoque Atualizado')], max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('link', models.CharField(blank=True, help_text='URL para o elemento relacionado', max_length=500, verbose_name='Link')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo do Objeto')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name='ID do Objeto')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='loja_notifi_user_id_d16eec_idx'), models.Index(fields=['user', '-created_at'], name='loja_notifi_user_id_26dc25_idx'), models.Index(fields=['-created_at'], name='loja_notifi_created_0340f8_idx')],
            },
        ),
    ]
