# Generated by Django 5.2.8 on 2025-11-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='browser',
            field=models.CharField(blank=True, max_length=100, verbose_name='Navegador'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='device_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome do Dispositivo'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='device_type',
            field=models.CharField(blank=True, help_text='Desktop, Mobile, Tablet', max_length=50, verbose_name='Tipo de Dispositivo'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do Produto'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço no momento da ação', max_digits=10, null=True, verbose_name='Preço do Produto'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='sale_number',
            field=models.CharField(blank=True, help_text='Número da venda relacionada', max_length=20, verbose_name='Número da Venda'),
        ),
    ]
